name: gym_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_size_text: 2.1.0
  convex_bottom_bar: ^3.0.0
  shared_preferences: ^2.0.7
  percent_indicator: ^3.0.1
  dotted_border: ^2.0.0+1
  persian_number_utility: ^0.3.4


  get: ^4.3.8

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: any

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/



  fonts:
    - family: IRANSans
      fonts:
        - asset: assets/fonts/dana-thin.ttf
          weight: 100
        - asset: assets/fonts/dana-extrabold.ttf
          weight: 800
        - asset: assets/fonts/dana-light.ttf
          weight: 400
        - asset: assets/fonts/dana-medium.ttf
          weight: 500
        - asset: assets/fonts/dana-regular.ttf
          weight: 400
        - asset: assets/fonts/dana-thin.ttf
          weight: 100
        - asset: assets/fonts/dana-ultrabold.ttf
          weight: 900
        - asset: assets/fonts/Quantify.ttf
          weight: 200
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
